README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

chore: add apns support

---

README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

Includes changes of Device count API, API spec lint errors fix, modification for EN Doc and pre prod
**Fixes:** #4555, #4280, #4455
Device Count API is not there.
list of Destination devices and Retrieves report of destination devices registered are present to be removed.
Tag subscription API are listing under Destination tag subscription.
Tags are unordered.
Lint errors.
Remove get list of Destination devices and Retrieves report of destination devices registered.
Add new header Push Destination API’s - to list all the tags and device count under this.
New Device count API 
Reordering of tags from Push Destination API’s (create, update, delete and listing)
Lint errors fixes.
signed-off-by: Nitish Kulkarni …

chore: add device count API, apispeclint errors fix and preprod

---

README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

Includes the changes of cloud functions as a destination 
**Fixes:** #4861
no cloud functions destination suppport
we can configure the cloud functions as a destination in EN

chore: add cloud functions destination support

---

README.md

updated readme on private end points.
**Fixes:** [5450](https://github.ibm.com/Notification-Hub/planning/issues/5450)
More explanation on private end point was missing.
Given more details on private end point configuration

chore: updated readme on private end point

---

eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go

PR includes example updates and test cases for push destinations.
Examples were not updated for push destinations
included examples and test cases for push destinations

chore: update examples and test cases

---

README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/6034)
Pagerduty destination support is not there
added Pagerduty destination support

chore: add PagerDuty destination

---

.secrets.baseline
eventnotificationsv1/event_notifications_v1_examples_test.go

Fixed for false positive audit checks and updated accordingly.
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/6684)
dummy values are used as secrets but detected as secrets in audit
removed dummy values and considered as false positive.

chore: fixed false positive audit checks

---

.secrets.baseline
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

Signed-off-by: Nitish Kulkarni <nitish.kulkarni3@ibm.com>
PR includes changes of support for new destination service now.
**Fixes:** <! -- [link to issue](https://github.ibm.com/Notification-Hub/planning/issues/6640) -->
no support of service now destination
added support for service now destination

chore: add Service Now Destination support 

---

.gitignore
.travis.yml
package.json

Signed-off-by: Nitish Kulkarni <nitish.kulkarni3@ibm.com>
configurations changes for semantic release
**Fixes:** <! -- (https://github.ibm.com/Notification-Hub/planning/issues/7182)-->
semantic release build is getting failed with node version 14
updated the project with new confuration for semantic release which uses node 14 and semantic release 19.0.5 version instead of 20.

chore: semantic release build issue fix

---

.secrets.baseline
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

Includes support for code engine as a destination.
**Fixes:** (https://github.ibm.com/Notification-Hub/planning/issues/7627)
Code engine destination support was not there
added support for code engine as destination

chore: add code engine destination support

---

eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

Inlcludes changes for COS destination support
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/7746)
there was no support for adding COS as a destination
Added support for adding COS as new destination

chore: adds COS destination support

---

eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

Signed-off-by: Nitish Kulkarni <nitish.kulkarni3@ibm.com>
PR include the changes Notification payload changes of huawei destination
**Fixes:** <! -- [link to issue ](https://github.ibm.com/notification-hub/planning/issues/8314)-->
* Notification payload was not updated.
* Notification payload changes for huawei

chore: notification payload changes huawei

---

.secrets.baseline
README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

Adds support for templates.
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/9860)
no support of templates
adds support for templates

chore: adds templates support

---

README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

notification payload changes for custom email- bypass subscription
**Fixes:** <! -- https://github.ibm.com/Notification-Hub/planning/issues/10427 -->
bypass subscription for custom email is not present
notification payload changes for custom email- bypass subscription

chore: custom email notification payload update

---

.secrets.baseline
README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

PR includes changes of test http destination connection
**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/10123)
currently test API for http destination connection was not there
includes test API for http destination connection

chore: add test http destination support

---

.secrets.baseline
.travis.yml
README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

slack direct message support
**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/14221
slack direct message was not supported
slack direct message is supported now.
Slack destination creation/update operation - DestinationConfigOneOfSlackDestinationConfig struct is added with one more attribute "type" to define the destination type. Supported types are "incoming_webhook" and "direct_message"

chore: support slack DM

---

.secrets.baseline
README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_test.go

https://github.ibm.com/Notification-Hub/planning/issues/16136
was having support for IBM cloud functions
Due to deprecation removing support of cloud functions

chore: removed cloud functions support

---

.secrets.baseline
README.md
common/headers.go
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

https://github.ibm.com/Notification-Hub/planning/issues/12339

feat: cron scheduler support

---

.secrets.baseline
README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go

**Fixes:** https://github.ibm.com/Notification-Hub/planning/issues/16809
there is no support for pagerduty templates
support for pagerduty template

chore: pagerduty template support

---

.github/workflows/ci.yml

chore: workflow change

---

.secrets.baseline
README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

**Fixes:** [<! -- link to issue -->](https://github.ibm.com/Notification-Hub/planning/issues/17206)
there is no support for Event Streams destination
support for Event Streams destination and template

chore: Events streams Destination and Template feature support

---

go.mod
go.sum

fix: vulnerability fix for golang.org/x/net package

---

.github/workflows/ci.yml

fix: go version release fix

---

.secrets.baseline
README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

chore: adds predefined templates support

---

.secrets.baseline
README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

**Fixes:** 
https://github.ibm.com/Notification-Hub/planning/issues/18346

feat: support for code engine templates

---

.secrets.baseline
README.md
eventnotificationsv1/event_notifications_v1.go
eventnotificationsv1/event_notifications_v1_examples_test.go
eventnotificationsv1/event_notifications_v1_integration_test.go
eventnotificationsv1/event_notifications_v1_test.go

https://github.ibm.com/Notification-Hub/planning/issues/18373

feat: appconfiguration destination support
